# Generated by Django 3.2.23 on 2024-01-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contactinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='Contact',
        ),
    ]
